#1 Task complete
Eduard-Bodreev/Yadro pull request #2
Opened 2024-03-29 12:51 UTC by Eduard-Bodreev

При запуске программа требует указания флага "-s", также предусмотрена возможность указания файла со стоп-словами через флаг "-stopwords". Список стоп-слов взят из открытых источников на GitHub Gist (https://gist.github.com/rg089/35e00abf8941d72d419224cfd5b5925d)

2024-03-29 15:07 UTC, vbelogrudov commented
все очень неплохо, было бы здорово еще добавить более умную разбивку, например, не только по пробелу, но и по табам, запятым ...

2024-03-29 15:13 UTC, Eduard-Bodreev commented
@vbelogrudov, Спасибо, завтра допишу разбивку и юнит-тесты

2024-03-29 15:33 UTC, kirreal commented
Проверил на строке:
Isn't she lovely? By the way I believe she's got it and I'd like being aroud.

результат lovely? aroud.

2024-03-29 15:34 UTC, kirreal requested changes

2024-03-29 15:34 UTC, kirreal commented on main.go
> +	input := flag.String("s", "", "String to normalize")
Тут проще использовать flag.StringVar(&input, ...) в таком случае не придется разименовывать указатель дальше

2024-03-29 15:34 UTC, kirreal commented on main.go
> +	normalizedWords := make([]string, 0)
Тут можно через var normalizedWords []string, через make с 0 не имеет особого смысла создавать

2024-03-29 15:34 UTC, kirreal commented on main.go
> +	words := strings.Fields(input)
Тут лучше попробовать использовать strings.FieldsFunc

2024-03-31 21:33 UTC, Eduard-Bodreev commented on main.go
> +	input := flag.String("s", "", "String to normalize")
https://github.com/Eduard-Bodreev/Yadro/pull/2/commits/d59994412776ce7841fef186e6a39b199e8d9db4#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R41

2024-03-31 21:36 UTC, Eduard-Bodreev commented on main.go
> +	normalizedWords := make([]string, 0)
https://github.com/Eduard-Bodreev/Yadro/blob/f8236df30ed81364a78891107b0670e5765bc0f3/main.go#L18

2024-03-31 21:37 UTC, Eduard-Bodreev commented on main.go
> +	words := strings.Fields(input)
https://github.com/Eduard-Bodreev/Yadro/pull/2/commits/d59994412776ce7841fef186e6a39b199e8d9db4#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R14

2024-03-31 21:38 UTC, Eduard-Bodreev commented
> Проверил на строке: Isn't she lovely? By the way I believe she's got it and I'd like being aroud.
> 
> результат lovely? aroud.

fixed (symbols)

2024-03-31 21:40 UTC, Eduard-Bodreev commented
> все очень неплохо, было бы здорово еще добавить более умную разбивку, например, не только по пробелу, но и по табам, запятым ...

https://github.com/Eduard-Bodreev/Yadro/pull/2/commits/d59994412776ce7841fef186e6a39b199e8d9db4#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R14

2024-04-01 07:49 UTC, vbelogrudov approved these changes
небольшие недочеты, можно доисправить в следующих заданиях при необходимости

2024-04-01 07:49 UTC, vbelogrudov commented on stopwords.go
> +	_, exists := stopwords[strings.ToLower(word)]
так как для стоп слов выбрана map[string]bool,
можно просто
return stopwords[strings.ToLower(word)]
при несуществующем ключе вернется дефолтное false

2024-04-01 07:49 UTC, vbelogrudov commented on main.go
> +	normalizedWords := make([]string, 0)
здесь достаточно var normalizedWords []string,
нулевой список и пустой для Го почти одинаков (для append, etc)

2024-04-01 07:49 UTC, vbelogrudov commented on main.go
> +			normalizedWords = append(normalizedWords, strings.ToLower(word)+" ")
лучше не склеивать слова, а отдавать их обратно слайсом. Пусть потребитель сам их склеит, если необходимо.

2024-04-01 07:49 UTC, vbelogrudov commented on main.go
> +			normalizedWords = append(normalizedWords, strings.ToLower(word)+" ")
+" " нет необходимости

2024-04-01 10:31 UTC, Eduard-Bodreev commented on stopwords.go
> +	_, exists := stopwords[strings.ToLower(word)]
https://github.com/Eduard-Bodreev/Yadro/pull/2/files#diff-48e79589d293e31de9f49b50d3521ba0976f5527f93852e4ef9878d86945b170R41

2024-04-01 10:32 UTC, Eduard-Bodreev commented on main.go
> +	normalizedWords := make([]string, 0)
https://github.com/Eduard-Bodreev/Yadro/pull/2/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R18

2024-04-01 10:33 UTC, Eduard-Bodreev commented on main.go
> +			normalizedWords = append(normalizedWords, strings.ToLower(word)+" ")
https://github.com/Eduard-Bodreev/Yadro/pull/2/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R28

2024-04-02 15:04 UTC, kirreal approved these changes

2024-04-02 18:48 UTC, merged